### ISSUE TITLE
Bakebot: use "allow-list" of ingredients rather than block bad ones

### ISSUE THREAD

**Issue by pahp** [UMDLARS/misconceptions-lab-ui#16]
For the "I can trust users" (input sanitization) exercise, we should have an allow-list (whitelist) of ingredients, rather than a list of blocked ingredients. The help text should say to enter the any legitimate ingredients from the recipes. (Right now, that's Flour, Sugar, Salt, Water).

**Comment by hijodecoche** [comment]
BakeBot should already be using a valid ingredients list, but I believe the regexes need to be improved.  I cleaned up the BakeBot activity intro text a bit.

**Comment by pahp** [comment]
As mentioned in Slack today, the issue I see is that it is a blocklist of bad ingredients, which is potentially infinite. Instead, we should have an "allow list" of only good ingredients: "Flour, Sugar, Salt, Water" (and it should be case-insensitive and we should say "a comma-separated list").
