### ISSUE TITLE
Bakebot: bakebot should refuse to bake with banned items

### ISSUE THREAD

**Issue by pahp** [UMDLARS/misconceptions-lab-ui#17]
When I use a banned item, it says that my humans are dead. 

![image](https://user-images.githubusercontent.com/15266857/84416654-1ca4bd00-abda-11ea-8a59-716b739a4456.png)

I think the behavior should be that Bakebot refuses to bake using "non approved" ingredients (see #16). I will make a "disapproving face" bot for that circumstance, because the current "refusal" image is too happy:

![image](https://user-images.githubusercontent.com/15266857/84416796-4fe74c00-abda-11ea-878d-1d6255bc9159.png)

**Comment by hijodecoche** [comment]
Changed the constraint from "illegal ingredients" to "approved ingredients."  When the user enters an unapproved ingredient, the message is "[ingredient] is not approved!"

**Comment by pahp** [comment]
![image](https://user-images.githubusercontent.com/15266857/84688274-b20abe80-af04-11ea-82e6-6c249370a6f2.png)
I'm Peter A. H. Peterson, and I approve this message.
