### ISSUE TITLE
issue with ingredient list not being processed correctly

### ISSUE THREAD

**Issue by pahp** [UMDLARS/misconceptions-lab-ui#22]
see image:
![image](https://user-images.githubusercontent.com/15266857/86392552-4002db00-bc61-11ea-9ef3-ab6e011c668c.png)

**Comment by pahp** [comment]
Adding "salt" to the list results in progress (the list is complete) but still complains that "flour is not in the list of approved ingredients"

**Comment by jnowaczek** [comment]
There also seems to be something wrong with the case conversion, this recipe will not work unless I lower case the ingredient allow list
![image](https://user-images.githubusercontent.com/8886072/86392773-9ec85480-bc61-11ea-88d1-c187f179a2e0.png)

**Comment by pahp** [comment]
> There also seems to be something wrong with the case conversion, this recipe will not work unless I lower case the ingredient allow list

This should also be fixed now -- same problem.
