### ISSUE TITLE
Icons render NULL text in Microsoft Edge

### ISSUE THREAD

**Issue by jnowaczek** [UMDLARS/misconceptions-lab-ui#3]
[Nebular issue](https://github.com/akveo/nebular/issues/1962)

This is not a bug with our project and will hopefully be fixed in the next Nebular release. @atr2600 implemented a workaround, but it's not pretty and adds a dependency on `jquery`. I suggest removing the workaround and waiting for the next Nebular release to fix the issue, in the mean time don't use Edge.

Thoughts?

**Comment by atr2600** [comment]
It seems that adding "else" branch to icon.component.ts fixes it (at least for IE):

    if (content) {
      this.html = this.sanitizer.bypassSecurityTrustHtml(content);
    }
    else { this.html = ""; }

**Comment by atr2600** [comment]
Did this fix not work??

**Comment by jnowaczek** [comment]
This bug has been fixed ages ago, I will remove the workaround code.
