### ISSUE TITLE
Create a timeout for bandwidth test

### ISSUE THREAD

**Issue by hijodecoche** [UMDLARS/misconceptions-lab-ui#39]
Egads! People with slower internet are being forced to download 10 MB!

**Comment by jnowaczek** [comment]
I think this should be pretty simple, we can add a timeout so the promise completes early if it’s a slow connection!

**Comment by hijodecoche** [comment]
Using Promise.race with the bandwidth test and a simple timeout function doesn't seem to be working. Maybe I'm missing a small detail, or maybe we need to test this on a truly slow internet connection instead of a rate limiter in Firefox.
